// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef compband_gui_h
#define compband_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include "RKR_Choice.h"
#include "RKR_GUI_Effect.h"
#include "RKR_Slider.h"
#include "../process.h"
#include "rakarrack.h"

class CbandGui : public RKR_Gui_Effect {
public:
  CbandGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *cband_activar;
private:
  inline void cb_cband_activar_i(RKR_Light_Button*, void*);
  static void cb_cband_activar(RKR_Light_Button*, void*);
public:
  RKR_Choice *cband_preset;
private:
  inline void cb_cband_preset_i(RKR_Choice*, void*);
  static void cb_cband_preset(RKR_Choice*, void*);
  static Fl_Menu_Item menu_cband_preset[];
public:
  RKR_Slider *cband_WD;
private:
  inline void cb_cband_WD_i(RKR_Slider*, void*);
  static void cb_cband_WD(RKR_Slider*, void*);
public:
  RKR_Slider *cband_gain;
private:
  inline void cb_cband_gain_i(RKR_Slider*, void*);
  static void cb_cband_gain(RKR_Slider*, void*);
public:
  RKR_Slider *cband_Lratio;
private:
  inline void cb_cband_Lratio_i(RKR_Slider*, void*);
  static void cb_cband_Lratio(RKR_Slider*, void*);
public:
  RKR_Slider *cband_MLratio;
private:
  inline void cb_cband_MLratio_i(RKR_Slider*, void*);
  static void cb_cband_MLratio(RKR_Slider*, void*);
public:
  RKR_Slider *cband_MHratio;
private:
  inline void cb_cband_MHratio_i(RKR_Slider*, void*);
  static void cb_cband_MHratio(RKR_Slider*, void*);
public:
  RKR_Slider *cband_Hratio;
private:
  inline void cb_cband_Hratio_i(RKR_Slider*, void*);
  static void cb_cband_Hratio(RKR_Slider*, void*);
public:
  RKR_Slider *cband_Lthres;
private:
  inline void cb_cband_Lthres_i(RKR_Slider*, void*);
  static void cb_cband_Lthres(RKR_Slider*, void*);
public:
  RKR_Slider *cband_MLthres;
private:
  inline void cb_cband_MLthres_i(RKR_Slider*, void*);
  static void cb_cband_MLthres(RKR_Slider*, void*);
public:
  RKR_Slider *cband_MHthres;
private:
  inline void cb_cband_MHthres_i(RKR_Slider*, void*);
  static void cb_cband_MHthres(RKR_Slider*, void*);
public:
  RKR_Slider *cband_Hthres;
private:
  inline void cb_cband_Hthres_i(RKR_Slider*, void*);
  static void cb_cband_Hthres(RKR_Slider*, void*);
public:
  RKR_Slider *cband_cross1;
private:
  inline void cb_cband_cross1_i(RKR_Slider*, void*);
  static void cb_cband_cross1(RKR_Slider*, void*);
public:
  RKR_Slider *cband_cross2;
private:
  inline void cb_cband_cross2_i(RKR_Slider*, void*);
  static void cb_cband_cross2(RKR_Slider*, void*);
public:
  RKR_Slider *cband_cross3;
private:
  inline void cb_cband_cross3_i(RKR_Slider*, void*);
  static void cb_cband_cross3(RKR_Slider*, void*);
public:
  void parameter_refresh(int index);
};
#endif
