// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef dflange_gui_h
#define dflange_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include "RKR_Check_Button.h"
#include "RKR_Choice.h"
#include <FL/Fl_Group.H>
#include "sliderW.h"
#include "../process.h"
#include "rakarrack.h"
#include "common_gui_menu.h"

class DflangeGui : public Fl_Group {
public:
  DflangeGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *dflange_activar;
private:
  inline void cb_dflange_activar_i(RKR_Light_Button*, void*);
  static void cb_dflange_activar(RKR_Light_Button*, void*);
public:
  RKR_Choice *dflange_preset;
private:
  inline void cb_dflange_preset_i(RKR_Choice*, void*);
  static void cb_dflange_preset(RKR_Choice*, void*);
  static Fl_Menu_Item menu_dflange_preset[];
public:
  SliderW *dflange_WD;
private:
  inline void cb_dflange_WD_i(SliderW*, void*);
  static void cb_dflange_WD(SliderW*, void*);
public:
  SliderW *dflange_pan;
private:
  inline void cb_dflange_pan_i(SliderW*, void*);
  static void cb_dflange_pan(SliderW*, void*);
public:
  SliderW *dflange_LR;
private:
  inline void cb_dflange_LR_i(SliderW*, void*);
  static void cb_dflange_LR(SliderW*, void*);
public:
  SliderW *dflange_depth;
private:
  inline void cb_dflange_depth_i(SliderW*, void*);
  static void cb_dflange_depth(SliderW*, void*);
public:
  SliderW *dflange_width;
private:
  inline void cb_dflange_width_i(SliderW*, void*);
  static void cb_dflange_width(SliderW*, void*);
public:
  SliderW *dflange_offset;
private:
  inline void cb_dflange_offset_i(SliderW*, void*);
  static void cb_dflange_offset(SliderW*, void*);
public:
  SliderW *dflange_fb;
private:
  inline void cb_dflange_fb_i(SliderW*, void*);
  static void cb_dflange_fb(SliderW*, void*);
public:
  SliderW *dflange_lpf;
private:
  inline void cb_dflange_lpf_i(SliderW*, void*);
  static void cb_dflange_lpf(SliderW*, void*);
public:
  RKR_Check_Button *dflange_subs;
private:
  inline void cb_dflange_subs_i(RKR_Check_Button*, void*);
  static void cb_dflange_subs(RKR_Check_Button*, void*);
public:
  RKR_Check_Button *dflange_tz;
private:
  inline void cb_dflange_tz_i(RKR_Check_Button*, void*);
  static void cb_dflange_tz(RKR_Check_Button*, void*);
public:
  RKR_Check_Button *dflange_intense;
private:
  inline void cb_dflange_intense_i(RKR_Check_Button*, void*);
  static void cb_dflange_intense(RKR_Check_Button*, void*);
public:
  SliderW *dflange_freq;
private:
  inline void cb_dflange_freq_i(SliderW*, void*);
  static void cb_dflange_freq(SliderW*, void*);
public:
  SliderW *dflange_stdf;
private:
  inline void cb_dflange_stdf_i(SliderW*, void*);
  static void cb_dflange_stdf(SliderW*, void*);
public:
  RKR_Choice *dflange_lfotype;
private:
  inline void cb_dflange_lfotype_i(RKR_Choice*, void*);
  static void cb_dflange_lfotype(RKR_Choice*, void*);
public:
  SliderW *dflange_rnd;
private:
  inline void cb_dflange_rnd_i(SliderW*, void*);
  static void cb_dflange_rnd(SliderW*, void*);
  CommonGuiMenu *m_lfo_menu; 
};
#endif
