// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef eq_gui_h
#define eq_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include "RKR_Choice.h"
#include "RKR_GUI_Effect.h"
#include "RKR_Slider.h"
#include "../process.h"
#include "rakarrack.h"

class EqGui : public RKR_Gui_Effect {
public:
  EqGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *eq_activar;
private:
  inline void cb_eq_activar_i(RKR_Light_Button*, void*);
  static void cb_eq_activar(RKR_Light_Button*, void*);
public:
  RKR_Choice *eq_preset;
private:
  inline void cb_eq_preset_i(RKR_Choice*, void*);
  static void cb_eq_preset(RKR_Choice*, void*);
  static Fl_Menu_Item menu_eq_preset[];
public:
  RKR_Slider *eq_Gain;
private:
  inline void cb_eq_Gain_i(RKR_Slider*, void*);
  static void cb_eq_Gain(RKR_Slider*, void*);
public:
  RKR_Slider *eq_Q;
private:
  inline void cb_eq_Q_i(RKR_Slider*, void*);
  static void cb_eq_Q(RKR_Slider*, void*);
public:
  RKR_Slider *eq_1;
private:
  inline void cb_eq_1_i(RKR_Slider*, void*);
  static void cb_eq_1(RKR_Slider*, void*);
public:
  RKR_Slider *eq_2;
private:
  inline void cb_eq_2_i(RKR_Slider*, void*);
  static void cb_eq_2(RKR_Slider*, void*);
public:
  RKR_Slider *eq_3;
private:
  inline void cb_eq_3_i(RKR_Slider*, void*);
  static void cb_eq_3(RKR_Slider*, void*);
public:
  RKR_Slider *eq_4;
private:
  inline void cb_eq_4_i(RKR_Slider*, void*);
  static void cb_eq_4(RKR_Slider*, void*);
public:
  RKR_Slider *eq_5;
private:
  inline void cb_eq_5_i(RKR_Slider*, void*);
  static void cb_eq_5(RKR_Slider*, void*);
public:
  RKR_Slider *eq_6;
private:
  inline void cb_eq_6_i(RKR_Slider*, void*);
  static void cb_eq_6(RKR_Slider*, void*);
public:
  RKR_Slider *eq_7;
private:
  inline void cb_eq_7_i(RKR_Slider*, void*);
  static void cb_eq_7(RKR_Slider*, void*);
public:
  RKR_Slider *eq_8;
private:
  inline void cb_eq_8_i(RKR_Slider*, void*);
  static void cb_eq_8(RKR_Slider*, void*);
public:
  RKR_Slider *eq_9;
private:
  inline void cb_eq_9_i(RKR_Slider*, void*);
  static void cb_eq_9(RKR_Slider*, void*);
public:
  RKR_Slider *eq_10;
private:
  inline void cb_eq_10_i(RKR_Slider*, void*);
  static void cb_eq_10(RKR_Slider*, void*);
public:
  void parameter_refresh(int index);
};
#endif
