// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "musdelay_gui.h"

void MusdelayGui::cb_musdelay_activar_i(Fl_Light_Button* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(116);
 o->value(rkr->MusDelay_Bypass);
 return;
}
rkr->MusDelay_Bypass=(int)o->value();
if((int) o->value()==0)
rkr->efx_MusDelay->cleanup();
rgui->findpos(15,(int)o->value(),o);
}
void MusdelayGui::cb_musdelay_activar(Fl_Light_Button* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_activar_i(o,v);
}

void MusdelayGui::cb_musdelay_preset_i(Fl_Choice* o, void* v) {
  rkr->MusDelay_Bypass=0;
long long ud= (long long) v;
if((ud==0)||(ud==12015))rkr->efx_MusDelay->setpreset(o->value());
musdelay_WD->value(rkr->efx_MusDelay->getpar(0));
musdelay_tempo->value(rkr->efx_MusDelay->getpar(10));
musdelay_pan1->value(rkr->efx_MusDelay->getpar(1)-64);
musdelay_pan2->value(rkr->efx_MusDelay->getpar(7)-64);
musdelay_delay1->value(rkr->efx_MusDelay->getpar(2)-1);
musdelay_delay2->value(rkr->efx_MusDelay->getpar(8)-1);
musdelay_delay3->value(rkr->efx_MusDelay->getpar(3)-1);
musdelay_fb1->value(rkr->efx_MusDelay->getpar(5));
musdelay_fb2->value(rkr->efx_MusDelay->getpar(9));
musdelay_LRc->value(rkr->efx_MusDelay->getpar(4)-64);
musdelay_gain1->value(rkr->efx_MusDelay->getpar(11)-64);
musdelay_gain2->value(rkr->efx_MusDelay->getpar(12)-64);
musdelay_damp->value(rkr->efx_MusDelay->getpar(6));
if((int)musdelay_activar->value())rkr->MusDelay_Bypass=1;
}
void MusdelayGui::cb_musdelay_preset(Fl_Choice* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_preset_i(o,v);
}

Fl_Menu_Item MusdelayGui::menu_musdelay_preset[] = {
 {"Echo 1", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"Echo 2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

void MusdelayGui::cb_musdelay_WD_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(56);
 return;
} 
rkr->efx_MusDelay->changepar(0,(int)o->value());
}
void MusdelayGui::cb_musdelay_WD(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_WD_i(o,v);
}

void MusdelayGui::cb_musdelay_LRc_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(98);
 return;
} 
rkr->efx_MusDelay->changepar(4,(int)o->value()+64);
}
void MusdelayGui::cb_musdelay_LRc(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_LRc_i(o,v);
}

void MusdelayGui::cb_musdelay_pan1_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(62);
 return;
} 
rkr->efx_MusDelay->changepar(1,(int)o->value()+64);
}
void MusdelayGui::cb_musdelay_pan1(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_pan1_i(o,v);
}

void MusdelayGui::cb_musdelay_pan2_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(65);
 return;
} 
rkr->efx_MusDelay->changepar(7,(int)o->value()+64);
}
void MusdelayGui::cb_musdelay_pan2(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_pan2_i(o,v);
}

void MusdelayGui::cb_musdelay_delay1_i(Fl_Choice* o, void*) {
  rkr->MusDelay_Bypass=0;
rkr->efx_MusDelay->changepar(2,o->value()+1);
if((int)musdelay_activar->value())rkr->MusDelay_Bypass=1;
}
void MusdelayGui::cb_musdelay_delay1(Fl_Choice* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_delay1_i(o,v);
}

Fl_Menu_Item MusdelayGui::menu_musdelay_delay1[] = {
 {"1", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/3", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/4", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/5", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/6", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

void MusdelayGui::cb_musdelay_delay3_i(Fl_Choice* o, void*) {
  rkr->MusDelay_Bypass=0;
rkr->efx_MusDelay->changepar(3,o->value()+1);
if((int)musdelay_activar->value())rkr->MusDelay_Bypass=1;
}
void MusdelayGui::cb_musdelay_delay3(Fl_Choice* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_delay3_i(o,v);
}

Fl_Menu_Item MusdelayGui::menu_musdelay_delay3[] = {
 {"1", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/3", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/4", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/5", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"1/6", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"0", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

void MusdelayGui::cb_musdelay_delay2_i(Fl_Choice* o, void*) {
  rkr->MusDelay_Bypass=0;
rkr->efx_MusDelay->changepar(8,o->value()+1);
if((int)musdelay_activar->value())rkr->MusDelay_Bypass=1;
}
void MusdelayGui::cb_musdelay_delay2(Fl_Choice* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_delay2_i(o,v);
}

void MusdelayGui::cb_musdelay_tempo_i(SliderW* o, void*) {
  rkr->MusDelay_Bypass=0;
rkr->efx_MusDelay->changepar(10,(int)o->value());
if((int)musdelay_activar->value())rkr->MusDelay_Bypass=1;
}
void MusdelayGui::cb_musdelay_tempo(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_tempo_i(o,v);
}

void MusdelayGui::cb_musdelay_gain1_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(24);
 return;
} 
rkr->efx_MusDelay->changepar(11,(int)o->value()+64);
}
void MusdelayGui::cb_musdelay_gain1(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_gain1_i(o,v);
}

void MusdelayGui::cb_musdelay_gain2_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(25);
 return;
} 
rkr->efx_MusDelay->changepar(12,(int)o->value()+64);
}
void MusdelayGui::cb_musdelay_gain2(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_gain2_i(o,v);
}

void MusdelayGui::cb_musdelay_fb1_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(83);
 return;
} 
rkr->efx_MusDelay->changepar(5,(int)o->value());
}
void MusdelayGui::cb_musdelay_fb1(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_fb1_i(o,v);
}

void MusdelayGui::cb_musdelay_fb2_i(SliderW* o, void*) {
  if(Fl::event_button()==3)
{
 rgui->getMIDIControl(84);
 return;
} 
rkr->efx_MusDelay->changepar(9,(int)o->value());
}
void MusdelayGui::cb_musdelay_fb2(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_fb2_i(o,v);
}

void MusdelayGui::cb_musdelay_damp_i(SliderW* o, void*) {
  rkr->efx_MusDelay->changepar(6,(int)o->value());
}
void MusdelayGui::cb_musdelay_damp(SliderW* o, void* v) {
  ((MusdelayGui*)(o->parent()))->cb_musdelay_damp_i(o,v);
}
MusdelayGui::MusdelayGui(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
this->box(FL_UP_BOX);
this->color(FL_FOREGROUND_COLOR);
this->selection_color(FL_FOREGROUND_COLOR);
this->user_data((void*)(1));
this->align(Fl_Align(96|FL_ALIGN_INSIDE));
{ musdelay_activar = new Fl_Light_Button(5, 4, 34, 18, "On");
  musdelay_activar->shortcut(0x35);
  musdelay_activar->color((Fl_Color)62);
  musdelay_activar->selection_color((Fl_Color)1);
  musdelay_activar->labelsize(10);
  musdelay_activar->callback((Fl_Callback*)cb_musdelay_activar, (void*)(2));
  musdelay_activar->align(Fl_Align(68|FL_ALIGN_INSIDE));
  musdelay_activar->when(FL_WHEN_CHANGED);
} // Fl_Light_Button* musdelay_activar
{ musdelay_preset = new Fl_Choice(77, 4, 76, 18, "Preset");
  musdelay_preset->down_box(FL_BORDER_BOX);
  musdelay_preset->selection_color(FL_FOREGROUND_COLOR);
  musdelay_preset->labelsize(10);
  musdelay_preset->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_preset->textsize(10);
  musdelay_preset->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_preset->callback((Fl_Callback*)cb_musdelay_preset, (void*)(12015));
  musdelay_preset->when(FL_WHEN_RELEASE_ALWAYS);
  musdelay_preset->menu(menu_musdelay_preset);
} // Fl_Choice* musdelay_preset
{ musdelay_WD = new SliderW(53, 26, 100, 10, "Wet/Dry");
  musdelay_WD->type(5);
  musdelay_WD->box(FL_FLAT_BOX);
  musdelay_WD->color((Fl_Color)178);
  musdelay_WD->selection_color((Fl_Color)62);
  musdelay_WD->labeltype(FL_NORMAL_LABEL);
  musdelay_WD->labelfont(0);
  musdelay_WD->labelsize(10);
  musdelay_WD->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_WD->maximum(127);
  musdelay_WD->step(1);
  musdelay_WD->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_WD->callback((Fl_Callback*)cb_musdelay_WD);
  musdelay_WD->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_WD->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_WD
{ musdelay_LRc = new SliderW(53, 38, 100, 10, "L/R.Cr");
  musdelay_LRc->type(5);
  musdelay_LRc->box(FL_FLAT_BOX);
  musdelay_LRc->color((Fl_Color)178);
  musdelay_LRc->selection_color((Fl_Color)62);
  musdelay_LRc->labeltype(FL_NORMAL_LABEL);
  musdelay_LRc->labelfont(0);
  musdelay_LRc->labelsize(10);
  musdelay_LRc->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_LRc->minimum(-64);
  musdelay_LRc->maximum(63);
  musdelay_LRc->step(1);
  musdelay_LRc->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_LRc->callback((Fl_Callback*)cb_musdelay_LRc);
  musdelay_LRc->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_LRc->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_LRc
{ musdelay_pan1 = new SliderW(53, 50, 100, 10, "Pan1");
  musdelay_pan1->type(5);
  musdelay_pan1->box(FL_FLAT_BOX);
  musdelay_pan1->color((Fl_Color)178);
  musdelay_pan1->selection_color((Fl_Color)62);
  musdelay_pan1->labeltype(FL_NORMAL_LABEL);
  musdelay_pan1->labelfont(0);
  musdelay_pan1->labelsize(10);
  musdelay_pan1->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_pan1->minimum(-64);
  musdelay_pan1->maximum(63);
  musdelay_pan1->step(1);
  musdelay_pan1->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_pan1->callback((Fl_Callback*)cb_musdelay_pan1);
  musdelay_pan1->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_pan1->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_pan1
{ musdelay_pan2 = new SliderW(53, 62, 100, 10, "Pan2");
  musdelay_pan2->type(5);
  musdelay_pan2->box(FL_FLAT_BOX);
  musdelay_pan2->color((Fl_Color)178);
  musdelay_pan2->selection_color((Fl_Color)62);
  musdelay_pan2->labeltype(FL_NORMAL_LABEL);
  musdelay_pan2->labelfont(0);
  musdelay_pan2->labelsize(10);
  musdelay_pan2->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_pan2->minimum(-64);
  musdelay_pan2->maximum(63);
  musdelay_pan2->step(1);
  musdelay_pan2->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_pan2->callback((Fl_Callback*)cb_musdelay_pan2);
  musdelay_pan2->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_pan2->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_pan2
{ musdelay_delay1 = new Fl_Choice(10, 82, 38, 14);
  musdelay_delay1->down_box(FL_BORDER_BOX);
  musdelay_delay1->labelsize(10);
  musdelay_delay1->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay1->textsize(10);
  musdelay_delay1->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay1->callback((Fl_Callback*)cb_musdelay_delay1, (void*)(12));
  musdelay_delay1->menu(menu_musdelay_delay1);
} // Fl_Choice* musdelay_delay1
{ musdelay_delay3 = new Fl_Choice(62, 82, 38, 14);
  musdelay_delay3->down_box(FL_BORDER_BOX);
  musdelay_delay3->labelsize(10);
  musdelay_delay3->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay3->textsize(10);
  musdelay_delay3->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay3->callback((Fl_Callback*)cb_musdelay_delay3, (void*)(12));
  musdelay_delay3->menu(menu_musdelay_delay3);
} // Fl_Choice* musdelay_delay3
{ Fl_Choice* o = musdelay_delay2 = new Fl_Choice(114, 82, 38, 14);
  musdelay_delay2->down_box(FL_BORDER_BOX);
  musdelay_delay2->labelsize(10);
  musdelay_delay2->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay2->textsize(10);
  musdelay_delay2->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_delay2->callback((Fl_Callback*)cb_musdelay_delay2);
  o->menu(menu_musdelay_delay1);
} // Fl_Choice* musdelay_delay2
{ musdelay_tempo = new SliderW(53, 103, 100, 10, "Tempo");
  musdelay_tempo->type(5);
  musdelay_tempo->box(FL_FLAT_BOX);
  musdelay_tempo->color((Fl_Color)178);
  musdelay_tempo->selection_color((Fl_Color)62);
  musdelay_tempo->labeltype(FL_NORMAL_LABEL);
  musdelay_tempo->labelfont(0);
  musdelay_tempo->labelsize(10);
  musdelay_tempo->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_tempo->minimum(10);
  musdelay_tempo->maximum(480);
  musdelay_tempo->step(1);
  musdelay_tempo->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_tempo->callback((Fl_Callback*)cb_musdelay_tempo);
  musdelay_tempo->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_tempo->when(FL_WHEN_RELEASE);
} // SliderW* musdelay_tempo
{ musdelay_gain1 = new SliderW(53, 122, 100, 10, "Gain1");
  musdelay_gain1->type(5);
  musdelay_gain1->box(FL_FLAT_BOX);
  musdelay_gain1->color((Fl_Color)178);
  musdelay_gain1->selection_color((Fl_Color)62);
  musdelay_gain1->labeltype(FL_NORMAL_LABEL);
  musdelay_gain1->labelfont(0);
  musdelay_gain1->labelsize(10);
  musdelay_gain1->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_gain1->minimum(-64);
  musdelay_gain1->maximum(63);
  musdelay_gain1->step(1);
  musdelay_gain1->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_gain1->callback((Fl_Callback*)cb_musdelay_gain1);
  musdelay_gain1->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_gain1->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_gain1
{ musdelay_gain2 = new SliderW(53, 134, 100, 10, "Gain2");
  musdelay_gain2->type(5);
  musdelay_gain2->box(FL_FLAT_BOX);
  musdelay_gain2->color((Fl_Color)178);
  musdelay_gain2->selection_color((Fl_Color)62);
  musdelay_gain2->labeltype(FL_NORMAL_LABEL);
  musdelay_gain2->labelfont(0);
  musdelay_gain2->labelsize(10);
  musdelay_gain2->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_gain2->minimum(-64);
  musdelay_gain2->maximum(63);
  musdelay_gain2->step(1);
  musdelay_gain2->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_gain2->callback((Fl_Callback*)cb_musdelay_gain2);
  musdelay_gain2->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_gain2->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_gain2
{ musdelay_fb1 = new SliderW(53, 146, 100, 10, "Fb1.");
  musdelay_fb1->type(5);
  musdelay_fb1->box(FL_FLAT_BOX);
  musdelay_fb1->color((Fl_Color)178);
  musdelay_fb1->selection_color((Fl_Color)62);
  musdelay_fb1->labeltype(FL_NORMAL_LABEL);
  musdelay_fb1->labelfont(0);
  musdelay_fb1->labelsize(10);
  musdelay_fb1->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_fb1->maximum(127);
  musdelay_fb1->step(1);
  musdelay_fb1->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_fb1->callback((Fl_Callback*)cb_musdelay_fb1);
  musdelay_fb1->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_fb1->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_fb1
{ musdelay_fb2 = new SliderW(53, 158, 100, 10, "Fb2.");
  musdelay_fb2->type(5);
  musdelay_fb2->box(FL_FLAT_BOX);
  musdelay_fb2->color((Fl_Color)178);
  musdelay_fb2->selection_color((Fl_Color)62);
  musdelay_fb2->labeltype(FL_NORMAL_LABEL);
  musdelay_fb2->labelfont(0);
  musdelay_fb2->labelsize(10);
  musdelay_fb2->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_fb2->maximum(127);
  musdelay_fb2->step(1);
  musdelay_fb2->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_fb2->callback((Fl_Callback*)cb_musdelay_fb2);
  musdelay_fb2->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_fb2->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_fb2
{ musdelay_damp = new SliderW(53, 170, 100, 10, "Damp");
  musdelay_damp->type(5);
  musdelay_damp->box(FL_FLAT_BOX);
  musdelay_damp->color((Fl_Color)178);
  musdelay_damp->selection_color((Fl_Color)62);
  musdelay_damp->labeltype(FL_NORMAL_LABEL);
  musdelay_damp->labelfont(0);
  musdelay_damp->labelsize(10);
  musdelay_damp->labelcolor(FL_BACKGROUND2_COLOR);
  musdelay_damp->maximum(127);
  musdelay_damp->step(1);
  musdelay_damp->textcolor(FL_BACKGROUND2_COLOR);
  musdelay_damp->callback((Fl_Callback*)cb_musdelay_damp);
  musdelay_damp->align(Fl_Align(FL_ALIGN_LEFT));
  musdelay_damp->when(FL_WHEN_CHANGED);
} // SliderW* musdelay_damp
position(X, Y);
end();
}
