// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef rbecho_gui_h
#define rbecho_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include <FL/Fl_Group.H>
#include "sliderW.h"
#include "../process.h"
#include "rakarrack.h"
#include "common_gui_menu.h"
#include <FL/Fl_Choice.H>

class RbechoGui : public Fl_Group {
public:
  RbechoGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *rbecho_activar;
private:
  inline void cb_rbecho_activar_i(RKR_Light_Button*, void*);
  static void cb_rbecho_activar(RKR_Light_Button*, void*);
public:
  Fl_Choice *rbecho_preset;
private:
  inline void cb_rbecho_preset_i(Fl_Choice*, void*);
  static void cb_rbecho_preset(Fl_Choice*, void*);
  static Fl_Menu_Item menu_rbecho_preset[];
public:
  SliderW *rbecho_WD;
private:
  inline void cb_rbecho_WD_i(SliderW*, void*);
  static void cb_rbecho_WD(SliderW*, void*);
public:
  SliderW *rbecho_RV;
private:
  inline void cb_rbecho_RV_i(SliderW*, void*);
  static void cb_rbecho_RV(SliderW*, void*);
public:
  SliderW *rbecho_pan;
private:
  inline void cb_rbecho_pan_i(SliderW*, void*);
  static void cb_rbecho_pan(SliderW*, void*);
public:
  SliderW *rbecho_delay;
private:
  inline void cb_rbecho_delay_i(SliderW*, void*);
  static void cb_rbecho_delay(SliderW*, void*);
public:
  SliderW *rbecho_LRdl;
private:
  inline void cb_rbecho_LRdl_i(SliderW*, void*);
  static void cb_rbecho_LRdl(SliderW*, void*);
public:
  SliderW *rbecho_fb;
private:
  inline void cb_rbecho_fb_i(SliderW*, void*);
  static void cb_rbecho_fb(SliderW*, void*);
public:
  Fl_Choice *rbecho_subdiv;
private:
  inline void cb_rbecho_subdiv_i(Fl_Choice*, void*);
  static void cb_rbecho_subdiv(Fl_Choice*, void*);
public:
  SliderW *rbecho_damp;
private:
  inline void cb_rbecho_damp_i(SliderW*, void*);
  static void cb_rbecho_damp(SliderW*, void*);
public:
  SliderW *rbecho_es;
private:
  inline void cb_rbecho_es_i(SliderW*, void*);
  static void cb_rbecho_es(SliderW*, void*);
public:
  SliderW *rbecho_angle;
private:
  inline void cb_rbecho_angle_i(SliderW*, void*);
  static void cb_rbecho_angle(SliderW*, void*);
  CommonGuiMenu *m_subdiv_menu; 
};
#endif
