// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef shuffle_gui_h
#define shuffle_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include "RKR_Check_Button.h"
#include "RKR_Choice.h"
#include "RKR_GUI_Effect.h"
#include "RKR_Slider.h"
#include "../process.h"
#include "rakarrack.h"

class ShuffleGui : public RKR_Gui_Effect {
public:
  ShuffleGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *shuffle_activar;
private:
  inline void cb_shuffle_activar_i(RKR_Light_Button*, void*);
  static void cb_shuffle_activar(RKR_Light_Button*, void*);
public:
  RKR_Choice *shuffle_preset;
private:
  inline void cb_shuffle_preset_i(RKR_Choice*, void*);
  static void cb_shuffle_preset(RKR_Choice*, void*);
  static Fl_Menu_Item menu_shuffle_preset[];
public:
  RKR_Slider *shuffle_WD;
private:
  inline void cb_shuffle_WD_i(RKR_Slider*, void*);
  static void cb_shuffle_WD(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_cross1;
private:
  inline void cb_shuffle_cross1_i(RKR_Slider*, void*);
  static void cb_shuffle_cross1(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_volL;
private:
  inline void cb_shuffle_volL_i(RKR_Slider*, void*);
  static void cb_shuffle_volL(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_cross2;
private:
  inline void cb_shuffle_cross2_i(RKR_Slider*, void*);
  static void cb_shuffle_cross2(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_volML;
private:
  inline void cb_shuffle_volML_i(RKR_Slider*, void*);
  static void cb_shuffle_volML(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_cross3;
private:
  inline void cb_shuffle_cross3_i(RKR_Slider*, void*);
  static void cb_shuffle_cross3(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_volMH;
private:
  inline void cb_shuffle_volMH_i(RKR_Slider*, void*);
  static void cb_shuffle_volMH(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_cross4;
private:
  inline void cb_shuffle_cross4_i(RKR_Slider*, void*);
  static void cb_shuffle_cross4(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_volH;
private:
  inline void cb_shuffle_volH_i(RKR_Slider*, void*);
  static void cb_shuffle_volH(RKR_Slider*, void*);
public:
  RKR_Slider *shuffle_Q;
private:
  inline void cb_shuffle_Q_i(RKR_Slider*, void*);
  static void cb_shuffle_Q(RKR_Slider*, void*);
public:
  RKR_Check_Button *shuffle_E;
private:
  inline void cb_shuffle_E_i(RKR_Check_Button*, void*);
  static void cb_shuffle_E(RKR_Check_Button*, void*);
public:
  void parameter_refresh(int index);
};
#endif
