// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef sustain_gui_h
#define sustain_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include "sliderW.h"
#include "../process.h"
#include "rakarrack.h"
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Choice.H>

class SustainGui : public Fl_Group {
public:
  SustainGui(int X, int Y, int W, int H, const char *L = 0);
  Fl_Light_Button *sus_activar;
private:
  inline void cb_sus_activar_i(Fl_Light_Button*, void*);
  static void cb_sus_activar(Fl_Light_Button*, void*);
public:
  Fl_Choice *sus_preset;
private:
  inline void cb_sus_preset_i(Fl_Choice*, void*);
  static void cb_sus_preset(Fl_Choice*, void*);
  static Fl_Menu_Item menu_sus_preset[];
public:
  SliderW *sus_gain;
private:
  inline void cb_sus_gain_i(SliderW*, void*);
  static void cb_sus_gain(SliderW*, void*);
public:
  SliderW *sus_sus;
private:
  inline void cb_sus_sus_i(SliderW*, void*);
  static void cb_sus_sus(SliderW*, void*);
};
#endif
