// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef vibe_gui_h
#define vibe_gui_h
#include <FL/Fl.H>
#include "RKR_Light_Button.h"
#include "RKR_Check_Button.h"
#include <FL/Fl_Group.H>
#include "sliderW.h"
#include "../process.h"
#include "rakarrack.h"
#include "common_gui_menu.h"
#include <FL/Fl_Choice.H>

class VibeGui : public Fl_Group {
public:
  VibeGui(int X, int Y, int W, int H, const char *L = 0);
  RKR_Light_Button *vibe_activar;
private:
  inline void cb_vibe_activar_i(RKR_Light_Button*, void*);
  static void cb_vibe_activar(RKR_Light_Button*, void*);
public:
  Fl_Choice *vibe_preset;
private:
  inline void cb_vibe_preset_i(Fl_Choice*, void*);
  static void cb_vibe_preset(Fl_Choice*, void*);
  static Fl_Menu_Item menu_vibe_preset[];
public:
  SliderW *vibe_WD;
private:
  inline void cb_vibe_WD_i(SliderW*, void*);
  static void cb_vibe_WD(SliderW*, void*);
public:
  SliderW *vibe_width;
private:
  inline void cb_vibe_width_i(SliderW*, void*);
  static void cb_vibe_width(SliderW*, void*);
public:
  SliderW *vibe_dpth;
private:
  inline void cb_vibe_dpth_i(SliderW*, void*);
  static void cb_vibe_dpth(SliderW*, void*);
public:
  SliderW *vibe_freq;
private:
  inline void cb_vibe_freq_i(SliderW*, void*);
  static void cb_vibe_freq(SliderW*, void*);
public:
  SliderW *vibe_rnd;
private:
  inline void cb_vibe_rnd_i(SliderW*, void*);
  static void cb_vibe_rnd(SliderW*, void*);
public:
  Fl_Choice *vibe_lfotype;
private:
  inline void cb_vibe_lfotype_i(Fl_Choice*, void*);
  static void cb_vibe_lfotype(Fl_Choice*, void*);
public:
  SliderW *vibe_stdf;
private:
  inline void cb_vibe_stdf_i(SliderW*, void*);
  static void cb_vibe_stdf(SliderW*, void*);
public:
  SliderW *vibe_fb;
private:
  inline void cb_vibe_fb_i(SliderW*, void*);
  static void cb_vibe_fb(SliderW*, void*);
public:
  SliderW *vibe_LR;
private:
  inline void cb_vibe_LR_i(SliderW*, void*);
  static void cb_vibe_LR(SliderW*, void*);
public:
  SliderW *vibe_pan;
private:
  inline void cb_vibe_pan_i(SliderW*, void*);
  static void cb_vibe_pan(SliderW*, void*);
public:
  RKR_Check_Button *vibe_stereo;
private:
  inline void cb_vibe_stereo_i(RKR_Check_Button*, void*);
  static void cb_vibe_stereo(RKR_Check_Button*, void*);
  CommonGuiMenu *m_lfo_menu; 
};
#endif
