// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef whawha_gui_h
#define whawha_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include "sliderW.h"
#include "../process.h"
#include "rakarrack.h"
#include "common_gui_menu.h"
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>

class WhawhaGui : public Fl_Group {
public:
  WhawhaGui(int X, int Y, int W, int H, const char *L = 0);
  Fl_Light_Button *WhaWha_activar;
private:
  inline void cb_WhaWha_activar_i(Fl_Light_Button*, void*);
  static void cb_WhaWha_activar(Fl_Light_Button*, void*);
public:
  Fl_Choice *WhaWha_preset;
private:
  inline void cb_WhaWha_preset_i(Fl_Choice*, void*);
  static void cb_WhaWha_preset(Fl_Choice*, void*);
  static Fl_Menu_Item menu_WhaWha_preset[];
public:
  SliderW *WhaWha_WD;
private:
  inline void cb_WhaWha_WD_i(SliderW*, void*);
  static void cb_WhaWha_WD(SliderW*, void*);
public:
  SliderW *WhaWha_pan;
private:
  inline void cb_WhaWha_pan_i(SliderW*, void*);
  static void cb_WhaWha_pan(SliderW*, void*);
public:
  SliderW *WhaWha_freq;
private:
  inline void cb_WhaWha_freq_i(SliderW*, void*);
  static void cb_WhaWha_freq(SliderW*, void*);
public:
  SliderW *WhaWha_rnd;
private:
  inline void cb_WhaWha_rnd_i(SliderW*, void*);
  static void cb_WhaWha_rnd(SliderW*, void*);
public:
  Fl_Choice *WhaWha_lfotype;
private:
  inline void cb_WhaWha_lfotype_i(Fl_Choice*, void*);
  static void cb_WhaWha_lfotype(Fl_Choice*, void*);
public:
  SliderW *WhaWha_stdf;
private:
  inline void cb_WhaWha_stdf_i(SliderW*, void*);
  static void cb_WhaWha_stdf(SliderW*, void*);
public:
  SliderW *WhaWha_dpth;
private:
  inline void cb_WhaWha_dpth_i(SliderW*, void*);
  static void cb_WhaWha_dpth(SliderW*, void*);
public:
  SliderW *WhaWha_ampsns;
private:
  inline void cb_WhaWha_ampsns_i(SliderW*, void*);
  static void cb_WhaWha_ampsns(SliderW*, void*);
public:
  Fl_Check_Button *WhaWha_ampsnsinv;
private:
  inline void cb_WhaWha_ampsnsinv_i(Fl_Check_Button*, void*);
  static void cb_WhaWha_ampsnsinv(Fl_Check_Button*, void*);
public:
  Fl_Choice *WhaWha_ftype;
private:
  inline void cb_WhaWha_ftype_i(Fl_Choice*, void*);
  static void cb_WhaWha_ftype(Fl_Choice*, void*);
  static Fl_Menu_Item menu_WhaWha_ftype[];
public:
  SliderW *WhaWha_smooth;
private:
  inline void cb_WhaWha_smooth_i(SliderW*, void*);
  static void cb_WhaWha_smooth(SliderW*, void*);
  CommonGuiMenu *m_lfo_menu; 
};
#endif
