set(UI_SOURCES
    ${CMAKE_SOURCE_DIR}/src/UI/rakarrack.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/analyzer.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/scope.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/newvum.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/tunerbar.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/common_gui_menu.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_GUI_Effect.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Input.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Box.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Browser.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Button.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Check_Button.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Choice.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Counter.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_File_Input.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Fl_Slider.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Float_Input.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Group.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Key_Input.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Light_Button.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Menu_Bar.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Slider.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Scroll.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Tabs.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/RKR_Value_Input.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/eq_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/compress_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/dist_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/ovrd_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/echo_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/chorus_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/phaser_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/flanger_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/reverb_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/peq_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/wahwah_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/alienwah_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/cabinet_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/pan_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/har_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/musdelay_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/gate_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/derelict_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/aphaser_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/valve_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/dflange_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/ring_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/exciter_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/distband_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/arpie_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/expander_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/shuffle_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/synthfilter_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/varyband_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/convo_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/looper_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/mutromojo_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/echoverse_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/coil_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/shelf_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/vocoder_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/sustain_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/sequence_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/shifter_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/stompbox_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/reverbtron_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/ressol_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/echotron_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/stereoharm_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/compband_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/otrem_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/vibe_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/infinity_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/midiconv_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/bankwindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/orderwindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/settingswindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/midilearnwindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/aboutwindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/trigwindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/delayfilewindow_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/randomedit_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/rkrprocess_gui.cxx
    ${CMAKE_SOURCE_DIR}/src/UI/Reset_Window.cpp
)
