set(FX_SOURCES
    ${CMAKE_SOURCE_DIR}/src/FX/Effect.C
    ${CMAKE_SOURCE_DIR}/src/FX/EQ.C
    ${CMAKE_SOURCE_DIR}/src/FX/Compressor.C
    ${CMAKE_SOURCE_DIR}/src/FX/Distorsion.C
    ${CMAKE_SOURCE_DIR}/src/FX/Overdrive.C
    ${CMAKE_SOURCE_DIR}/src/FX/Echo.C
    ${CMAKE_SOURCE_DIR}/src/FX/Chorus.C
    ${CMAKE_SOURCE_DIR}/src/FX/Flanger.C
    ${CMAKE_SOURCE_DIR}/src/FX/APhaser.C
    ${CMAKE_SOURCE_DIR}/src/FX/Harmonizer.C
    ${CMAKE_SOURCE_DIR}/src/FX/Sustainer.C
    ${CMAKE_SOURCE_DIR}/src/FX/Exciter.C
    ${CMAKE_SOURCE_DIR}/src/FX/Pan.C
    ${CMAKE_SOURCE_DIR}/src/FX/Alienwah.C
    ${CMAKE_SOURCE_DIR}/src/FX/Reverb.C
    ${CMAKE_SOURCE_DIR}/src/FX/Cabinet.C
    ${CMAKE_SOURCE_DIR}/src/FX/MusicDelay.C
    ${CMAKE_SOURCE_DIR}/src/FX/WahWah.C
    ${CMAKE_SOURCE_DIR}/src/FX/Derelict.C
    ${CMAKE_SOURCE_DIR}/src/FX/Valve.C
    ${CMAKE_SOURCE_DIR}/src/FX/Dual_Flange.C
    ${CMAKE_SOURCE_DIR}/src/FX/Ring.C
    ${CMAKE_SOURCE_DIR}/src/FX/DistBand.C
    ${CMAKE_SOURCE_DIR}/src/FX/Arpie.C
    ${CMAKE_SOURCE_DIR}/src/FX/Expander.C
    ${CMAKE_SOURCE_DIR}/src/FX/Shuffle.C
    ${CMAKE_SOURCE_DIR}/src/FX/Synthfilter.C
    ${CMAKE_SOURCE_DIR}/src/FX/VaryBand.C
    ${CMAKE_SOURCE_DIR}/src/FX/MuTroMojo.C
    ${CMAKE_SOURCE_DIR}/src/FX/Echoverse.C
    ${CMAKE_SOURCE_DIR}/src/FX/CoilCrafter.C
    ${CMAKE_SOURCE_DIR}/src/FX/ShelfBoost.C
    ${CMAKE_SOURCE_DIR}/src/FX/Vocoder.C
    ${CMAKE_SOURCE_DIR}/src/FX/Sequence.C
    ${CMAKE_SOURCE_DIR}/src/FX/Shifter.C
    ${CMAKE_SOURCE_DIR}/src/FX/StompBox.C
    ${CMAKE_SOURCE_DIR}/src/FX/Reverbtron.C
    ${CMAKE_SOURCE_DIR}/src/FX/Echotron.C
    ${CMAKE_SOURCE_DIR}/src/FX/StereoHarm.C
    ${CMAKE_SOURCE_DIR}/src/FX/CompBand.C
    ${CMAKE_SOURCE_DIR}/src/FX/Opticaltrem.C
    ${CMAKE_SOURCE_DIR}/src/FX/Vibe.C
    ${CMAKE_SOURCE_DIR}/src/FX/Infinity.C
    ${CMAKE_SOURCE_DIR}/src/FX/Phaser.C
    ${CMAKE_SOURCE_DIR}/src/FX/Gate.C
    ${CMAKE_SOURCE_DIR}/src/FX/Convolotron.C
    ${CMAKE_SOURCE_DIR}/src/FX/ParametricEQ.C
    ${CMAKE_SOURCE_DIR}/src/FX/ResSolution.C
    ${CMAKE_SOURCE_DIR}/src/FX/MIDIConverter.C
)

set(EFX_COMMON_SOURCES
    ${CMAKE_SOURCE_DIR}/src/EFX_common/AnalogFilter.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/Waveshaper.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/Resample.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/FPreset.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/delayline.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/EffectLFO.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/smbPitchShift.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/pffft.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/HarmonicEnhancer.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/Filter.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/FilterParams.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/SVFilter.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/FormantFilter.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/RBFilter.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/beattracker.C
    ${CMAKE_SOURCE_DIR}/src/EFX_common/mayer_fft.C
)
